source 'https://supermarket.chef.io'

metadata

group :delivery do
  cookbook 'delivery_build', git: 'https://github.com/chef-cookbooks/delivery_build'
  cookbook 'delivery-base', git: 'https://github.com/chef-cookbooks/delivery-base'
  cookbook 'coffee-truck', git: 'https://github.com/zamedic/coffee-truck.git', branch: 'docs'
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
